# Generated by Django 6.0.1 on 2026-02-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showseat',
            name='seat',
        ),
        migrations.AddField(
            model_name='showseat',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showseat',
            name='row',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
