# Generated by Django 6.0.1 on 2026-02-05 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_showseat_seat_showseat_number_showseat_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showseat',
            name='row',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='showseat',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.show'),
        ),
    ]
