# Generated by Django 6.0.1 on 2026-02-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_showseat_row_alter_showseat_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(to='booking.showseat'),
        ),
    ]
