# Generated by Django 5.2.1 on 2026-02-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_showseat_reserved_at_showseat_reserved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
