# Generated by Django 6.0.1 on 2026-02-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Action', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='English', max_length=50),
            preserve_default=False,
        ),
    ]
