# Generated by Django 6.0.1 on 2026-02-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_genre_movie_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='theater',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Theater',
        ),
    ]
