# Generated by Django 4.2.28 on 2026-02-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_seat_theater_remove_theater_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='YouTube trailer URL (e.g., https://www.youtube.com/watch?v=xxxxx)', null=True),
        ),
    ]
